version: "3.8"

services:
  nginx:
    image: nginx:1.14.2
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html/
  php:
    image: php:8.4.0alpha4-fpm
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/