version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html/
  php:
    build: ./php/
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/