version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/usr/share/nginx/html/
  php:
    image: php-git
    expose:
      - 9000
    volumes:
      - ./:/usr/share/nginx/html/