services:
  nginx:
    image: nginx:1.14.2
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site/:/var/www/html/
    links:
      - php
  php:
    image: php:8-fpm
    volumes:
      - ./site/:/var/www/html/